/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as VendorRegisterRouteImport } from './routes/vendor-register'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorQuotationResponseTokenRouteImport } from './routes/vendor-quotation-response.$token'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor-register',
  path: '/vendor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorQuotationResponseTokenRoute =
  VendorQuotationResponseTokenRouteImport.update({
    id: '/vendor-quotation-response/$token',
    path: '/vendor-quotation-response/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/supplier': typeof SupplierRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/workshop': typeof WorkshopRoute
  '/vendor-quotation-response/$token': typeof VendorQuotationResponseTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/supplier': typeof SupplierRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/workshop': typeof WorkshopRoute
  '/vendor-quotation-response/$token': typeof VendorQuotationResponseTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/supplier': typeof SupplierRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/workshop': typeof WorkshopRoute
  '/vendor-quotation-response/$token': typeof VendorQuotationResponseTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/supplier'
    | '/vendor-register'
    | '/workshop'
    | '/vendor-quotation-response/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/supplier'
    | '/vendor-register'
    | '/workshop'
    | '/vendor-quotation-response/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/supplier'
    | '/vendor-register'
    | '/workshop'
    | '/vendor-quotation-response/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SupplierRoute: typeof SupplierRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  WorkshopRoute: typeof WorkshopRoute
  VendorQuotationResponseTokenRoute: typeof VendorQuotationResponseTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-register': {
      id: '/vendor-register'
      path: '/vendor-register'
      fullPath: '/vendor-register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-quotation-response/$token': {
      id: '/vendor-quotation-response/$token'
      path: '/vendor-quotation-response/$token'
      fullPath: '/vendor-quotation-response/$token'
      preLoaderRoute: typeof VendorQuotationResponseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SupplierRoute: SupplierRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  WorkshopRoute: WorkshopRoute,
  VendorQuotationResponseTokenRoute: VendorQuotationResponseTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
